package hr.fer.zemris.java.gui.prim;

import javax.swing.*;
import java.awt.*;

/**
 * This class is used for showing two lists of same prime numbers. New numbers can be generated by pressing on button
 * next.
 */
public class PrimDemo extends JFrame {

    /**
     * Basic constructor.
     */
    public PrimDemo() {
        super();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PrimDemo");
        setLocation(20, 20);
        setSize(300, 300);
        initGUI();
    }

    /**
     * This class is used for initializing graphical user interface.
     */
    private void initGUI() {
        Container cp = getContentPane();
        cp.setLayout(new BorderLayout());
        cp.setBackground(Color.WHITE);

        ListModel<Integer> model = new PrimListModel();

        JScrollPane list1 = new JScrollPane(new JList<>(model));
        JScrollPane list2 = new JScrollPane(new JList<>(model));

        JPanel listPanel = new JPanel();
        listPanel.setLayout(new GridLayout(0, 2));
        listPanel.add(list1);
        listPanel.add(list2);

        cp.add(listPanel, BorderLayout.CENTER);

        JButton next = new JButton("Next");
        next.addActionListener(e -> ((PrimListModel) model).next());
        cp.add(next, BorderLayout.SOUTH);

    }


    /**
     * Main method.
     *
     * @param args Command line arguments
     */
    public static void main(String[] args) {

        SwingUtilities.invokeLater(() -> {
            PrimDemo prozor = new PrimDemo();
            prozor.setVisible(true);
        });
    }
}
